version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    working_directory: /go/src/github.com/logv/sybil

    steps:
      - checkout
      - run: mkdir -p /tmp/test-results

      - run: make deps

      - run: make

      - run: go get github.com/alecthomas/gometalinter
      - run: go get github.com/bradleyfalzon/revgrep/cmd/revgrep
      - run:
          name: Run linters
          command: |
            gometalinter -i > /dev/null
            make lint

      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report </tmp/test-results/go-test.out > /tmp/test-results/go-test-report.xml" EXIT
            make testv | tee /tmp/test-results/go-test.out

      - run:
          name: Run code coverage
          command: |
            make coverage
            cp cover.html /tmp/test-results
            bash <(curl -s https://codecov.io/bash) -c -F unittests

      - run:
          name: Run fuzz coverage
          command: |
            go install
            make fuzzcoverage
            cp fuzzcover.html /tmp/test-results
            bash <(curl -s https://codecov.io/bash) -c -F fuzztests -f fuzzcover.out

      - run:
          name: Run benchmarks
          command: ./scripts/ci_run_benchmarks.sh

      - run:
          name: Run code coverage
          command: |
            make coverage
            cp cover.html /tmp/test-results
            bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
  build16:
    docker:
      - image: golang:1.6
    working_directory: /go/src/github.com/logv/sybil
    steps:
      - checkout
      - run: make deps
      - run: make
      - run: mkdir -p /tmp/test-results
      - run: ./scripts/ci_run_benchmarks.sh
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
  build17:
    docker:
      - image: golang:1.7
    working_directory: /go/src/github.com/logv/sybil
    steps:
      - checkout
      - run: make deps
      - run: make
      - run: mkdir -p /tmp/test-results
      - run: ./scripts/ci_run_benchmarks.sh
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
  build18:
    docker:
      - image: golang:1.8
    working_directory: /go/src/github.com/logv/sybil
    steps:
      - checkout
      - run: make deps
      - run: make
      - run: mkdir -p /tmp/test-results
      - run: ./scripts/ci_run_benchmarks.sh
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build16
      - build17
      - build18
